
GET_PROPERTY(dirs TARGET ${PROJECT_NAME} PROPERTY INCLUDE_DIRECTORIES)
set_target_properties(${PROJECT_NAME} PROPERTIES FOLDER "Plugins")
FILE(READ "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}_config.txt" temp)
SET(PROJECT_ID)
IF(temp)
  STRING(FIND "${temp}" "\n" len)
  STRING(SUBSTRING "${temp}" 0 ${len} temp)
  SET(PROJECT_ID ${temp})
ELSE(temp)
  SET(PROJECT_ID "1")
ENDIF(temp)
LIST(REMOVE_DUPLICATES dirs)
LIST(REMOVE_DUPLICATES LINK_DIRS_RELEASE)
LIST(REMOVE_DUPLICATES LINK_DIRS_DEBUG)

FILE(WRITE "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}_config.txt" "${PROJECT_ID}\n${dirs};\n${LINK_DIRS_DEBUG};\n${LINK_DIRS_RELEASE};\n-DPROJECT_BUILD_DIR=\"${CMAKE_CURRENT_BINARY_DIR}\";${DEFS}")

ADD_DEFINITIONS(-DPROJECT_BUILD_DIR="${CMAKE_CURRENT_BINARY_DIR}")
ADD_DEFINITIONS(-DPROJECT_CONFIG_FILE=\"${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}_config.txt\")
LINK_DIRECTORIES(${LINK_DIRS_DEBUG})
LINK_DIRECTORIES(${LINK_DIRS_RELEASE})
#cotire(${PROJECT_NAME})
MESSAGE(STATUS 
"====== ${PROJECT_NAME} ======

 Project ID: ${PROJECT_ID}
 
 Config file: ${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}_config.txt
 
 Headers: 
 ${hdr}
 
 Source: 
 ${src}
 
 Cuda kernels: 
 ${knl}
 
 QT MOC: 
 ${MOC}
 
 Definitions:
 ${DEFS}
 
 C++ flags:
  ${CMAKE_CXX_FLAGS}
 Debug:
  ${CMAKE_CXX_FLAGS_DEBUG}
 Release:
  ${CMAKE_CXX_FLAGS_RELEASE}
 C Flags
  ${CMAKE_C_FLAGS}
  Include Dirs: ${dirs}
  
  Link Dirs Debug: ${LINK_DIRS_DEBUG}
  
  Link Dirs Release: ${LINK_DIRS_RELEASE}
 ")
