###############################################################################
# Find Flann
#
# This sets the following variables:
# FLANN_FOUND - True if FLANN was found.
# FLANN_INCLUDE_DIRS - Directories containing the FLANN include files.
# FLANN_LIBRARIES - Libraries needed to use FLANN.
# FLANN_DEFINITIONS - Compiler flags for FLANN.


find_path(EAGLELIB_FLANN_INCLUDE_DIR flann/flann.hpp
    HINTS ${PC_FLANN_INCLUDEDIR} ${PC_FLANN_INCLUDE_DIRS})

find_library(EAGLELIB_FLANN_LIBRARY_DEBUG flann_cpp_s
    HINTS ${PC_FLANN_LIBDIR} ${PC_FLANN_LIBRARY_DIRS})
find_library(EAGLELIB_FLANN_LIBRARY_RELEASE flann_cpp_sd

    HINTS ${PC_FLANN_LIBDIR} ${PC_FLANN_LIBRARY_DIRS})
	
find_library(EAGLELIB_FLANN_CUDA_LIBRARY_RELEASE flann_cuda_sd
	HINTS ${PC_FLANN_LIBDIR} ${PC_FLANN_LIBRARY_DIRS})
	
find_library(EAGLELIB_FLANN_CUDA_LIBRARY_DEBUG flann_cuda_sd
	HINTS ${PC_FLANN_LIBDIR} ${PC_FLANN_LIBRARY_DIRS})
	
set(EAGLELIB_FLANN_INCLUDE_DIRS ${FLANN_INCLUDE_DIR})
set(EAGLELIB_FLANN_LIBRARIES "debug;${EAGLELIB_FLANN_LIBRARY_DEUBG};optimzied;${EAGLELIB_FLANN_LIBRARY_RELEASE};debug;${EAGLELIB_FLANN_CUDA_LIBRARY_DEBUG};optimized;${EAGLELIB_FLANN_CUDA_LIBRARY_RELEASE}")

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Flann DEFAULT_MSG
    EAGLELIB_FLANN_LIBRARY_DEBUG EAGLELIB_FLANN_INCLUDE_DIR)

mark_as_advanced(EAGLELIB_FLANN_LIBRARY_DEBUG EAGLELIB_FLANN_LIBRARY_RELEASE EAGLELIB_FLANN_CUDA_LIBRARY_RELEASE EAGLELIB_FLANN_CUDA_LIBRARY_DEBUG EAGLELIB_FLANN_LIBRARIES EAGLELIB_FLANN_INCLUDE_DIR)